spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bancario
    username: root
    password: admin123
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
